[FIX] Rocket.Chat 3.0.12 Livechat issue about Korean IME #403
RocketChat/Rocket.Chat.Livechat pull request #538
Opened 2020-12-04 08:59 UTC by ian902792

This way can fix IME input method problem(Such as, Korean、Japanese、Chinese).
Because preact.js has SyntheticEvent issue.
Therefore, oncompositionstart & oncompositionend are all lowercase.
[Reference](https://github.com/preactjs/preact/issues/1978)

2020-12-04 09:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat.Livechat?pullRequest=538) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat.Livechat?pullRequest=538) before we can accept your contribution.<br/><hr/>**ian.yu** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat.Livechat?pullRequest=538) it.</sub>

2020-12-07 06:53 UTC, ian902792 commented
Contributor License Agreement page show "You have agreed to the CLA for RocketChat/Rocket.Chat.Livechat"
but GitHub comment's CLA status show " not signed yet".
So...?

2021-03-08 06:54 UTC, sctEdwin commented
May I asked when will this be merged?
Japanese IME conversion is also fixed by this pull request.

2021-03-12 17:59 UTC, rafaelblink approved these changes

2021-03-15 16:40 UTC, renatobecker requested changes

2021-03-15 16:40 UTC, renatobecker commented on src/components/Composer/index.js
> +let inputLock = false;
Why did you implement a global variable rather than an internal state variable?

2021-03-15 16:40 UTC, renatobecker commented on src/components/Composer/index.js
> +		if (!inputLock) {
```suggestion
		if (inputLock) {
			return;
		}
		
		onChange && onChange(this.el.innerText);
```

2021-03-15 16:40 UTC, renatobecker commented on src/components/Composer/index.js
> +				oncompositionstart={(e)=>{
```suggestion
				onCompositionStart={(e)=>{
```
Use camelCase to write event names: https://reactjs.org/docs/events.html#composition-events

2022-01-20 17:31 UTC, tiagoevanp commented
Thank you @ian902792 for the suggestion!

In the future we will improve the composer as a more complex input component. For now is more concise to deal with the problem in that way:  https://github.com/RocketChat/Rocket.Chat.Livechat/pull/674

2022-01-20 17:31 UTC, closed without merging