[FEATURE] New trigger messages style
RocketChat/Rocket.Chat.Livechat pull request #553
Opened 2021-02-11 22:53 UTC by rafaelblink

2021-02-18 19:27 UTC, dougfabris requested changes
@rafaelblink really nice improvements! I found some points to discuss: 

1. I think we shouldn't render empty triggers:
![image](https://user-images.githubusercontent.com/27704687/108409887-81062a80-7205-11eb-931d-cd2d79bf448f.png)
2. To improve more the second point, maybe we can add a UI validation not allowing the creation of triggers with the message field empty
3. It's not possible to run the storybook. I think it's something wrong in  @rocket.chat/ui-kit package version. It fires an error on `src/components/uiKit/message/index.js`

2021-02-18 20:58 UTC, renatobecker requested changes
![Screen Shot 2021-02-18 at 5 56 36 PM](https://user-images.githubusercontent.com/59577424/108420566-bebd8000-7212-11eb-8864-bedb30d1ec10.png)

The new component is not following the design system(figma).

![Screen Shot 2021-02-18 at 5 58 14 PM](https://user-images.githubusercontent.com/59577424/108420693-e7457a00-7212-11eb-85e7-dbf771dd2d30.png)

2021-02-19 12:50 UTC, rafaelblink commented
> @rafaelblink really nice improvements! I found some points to discuss:
> 
> 1. I think we shouldn't render empty triggers:
>    ![image](https://user-images.githubusercontent.com/27704687/108409887-81062a80-7205-11eb-931d-cd2d79bf448f.png)
> 2. To improve more the second point, maybe we can add a UI validation not allowing the creation of triggers with the message field empty
> 3. It's not possible to run the storybook. I think it's something wrong in  @rocket.chat/ui-kit package version. It fires an error on `src/components/uiKit/message/index.js`

PR created to solve this: https://github.com/RocketChat/Rocket.Chat/pull/20827

About storybook, its running here, I'm running with `yarn storybook`

![image](https://user-images.githubusercontent.com/2493803/108506587-cf640980-7297-11eb-89e5-8a591ab1795d.png)

2021-02-19 14:48 UTC, dougfabris approved these changes

2021-02-19 14:54 UTC, merged