[FIX] sound notification on/off
RocketChat/Rocket.Chat.Livechat pull request #567
Opened 2021-03-21 20:25 UTC by Deepak-learner

[FIX] issue #376 
While clicking on notification toggle button, now tooltip value is also updating on UI with its state .
Additional context :

https://user-images.githubusercontent.com/56799414/111919765-a3fc5680-8ab1-11eb-9025-83eaf323c73b.mov

2021-03-21 20:31 UTC, Deepak-learner commented
@rafaelblink , @murtaza98 please review.

2021-04-14 18:08 UTC, rafaelblink requested changes
Hi @Deepak-learner, I did some code requests, not complex stuff, if it's possible, please install `ESLint` on your code editor.

2021-04-14 18:08 UTC, rafaelblink commented on src/components/Tooltip/index.js
> +			content: content
```suggestion
			content,
```

2021-04-14 18:08 UTC, rafaelblink commented on src/components/Tooltip/index.js
> +	componentWillReceiveProps(props) {
```suggestion
	UNSAFE_componentWillReceiveProps(props) {
```

2021-04-14 18:08 UTC, rafaelblink commented on src/components/Tooltip/index.js
> +		if(this.state.tooltip) {
```suggestion
		if (this.state.tooltip) {
```

2021-04-14 18:08 UTC, rafaelblink commented on src/components/Tooltip/index.js
> +			const activeChildren = props.children && props.children.props && props.children.props.children ? props.children.props.children[this.state.activeChild] : null;
```suggestion
			const activeChildren = props?.children?.props?.children[this.state.activeChild];
```

2021-04-14 18:08 UTC, rafaelblink commented on src/components/Tooltip/index.js
> +			if(activeChildren && activeChildren.props.content !== this.state.content) {
```suggestion
			if (activeChildren && activeChildren.props.content !== this.state.content) {
```

2021-04-14 18:08 UTC, rafaelblink commented on src/components/Tooltip/index.js
> +		this.setState({ tooltip: <Tooltip floating placement={placement} triggerBounds={triggerBounds}>{content}</Tooltip>, activeChild: childIndex, event: event, placement: placement, content: content });
```suggestion
		this.setState({ tooltip: <Tooltip floating placement={placement} triggerBounds={triggerBounds}>{content}</Tooltip>, activeChild: childIndex, event, placement, content });
```

2021-04-14 18:08 UTC, rafaelblink commented on src/components/Tooltip/index.js
> +		placement: null
```suggestion
		placement: null,
```

2021-04-14 19:56 UTC, Deepak-learner commented
@rafaelblink I make the necessary changes suggested by you. Please review.

2021-04-14 20:44 UTC, Deepak-learner commented
Hey @rafaelblink, I make the necessary changes suggested by you. Please review.

2021-04-16 12:29 UTC, rafaelblink approved these changes

2021-04-21 03:32 UTC, merged