Hotfix/theme conflict bodyStyle variable (body.style attribute) #572
RocketChat/Rocket.Chat.Livechat pull request #619
Opened 2021-07-14 16:24 UTC by idevit

This pull request fixes bodyStyle variable (body.style attribute) #572

https://github.com/RocketChat/Rocket.Chat.Livechat/issues/572

2021-07-14 16:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat.Livechat?pullRequest=619) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat.Livechat?pullRequest=619) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: idevit<br/>:white_check_mark: bkrith<br/>:x: Gospodin P.Zh<br/><hr/>**Gospodin P.Zh** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat.Livechat?pullRequest=619) it.</sub>

2021-09-13 16:11 UTC, MartinSchoeler requested changes
Hello! Could you do a rebase to the current develop? It seems that we have some conflicting changes in here. Thanks!

2021-09-13 16:11 UTC, MartinSchoeler commented on yarn.lock
> -# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
Could you please undo this deletion? Thanks!

2021-10-29 23:00 UTC, idevit commented
why is the lock not in the gitignore?
sorry for responding late were looking into it

2021-10-30 15:18 UTC, idevit commented
it should be ok now?

2021-11-19 14:58 UTC, murtaza98 commented
@idevit Thanks for the contribution!! I found some issues with this PR while testing. The thing is, scrolling stopped working on mobile devices, as soon a widget was opened and then closed. I believe this was a result of adding these 2 extra CSS attributes to the body -> `position: fixed; top: ${ scrollPosition }px;` 

So, I've created a PR https://github.com/RocketChat/Rocket.Chat.Livechat/pull/660 to fix this and also simplified the logic for handling styles by grouping those styles into a single class. Feel free to test the change and share your findings. Thanks!!

2021-11-19 15:02 UTC, closed without merging