[IMPROVE] Replace i18n package
RocketChat/Rocket.Chat.Livechat pull request #657
Opened 2021-10-26 21:07 UTC by tiagoevanp

2021-11-10 16:06 UTC, KevLehman commented
@tiagoevanp , CI is failing :(

2021-11-16 16:28 UTC, murtaza98 commented on src/i18n/pt-BR.json
> +        "chat_now": "Converse agora",
```suggestion
        "chat_now": "Converse agora",
        "chat_started": "Bate-papo iniciado",
```

2021-11-16 16:30 UTC, murtaza98 commented on src/i18n/fr.json
> +        "chat_finished": "Chat Terminé",
```suggestion
        "chat_finished": "Chat Terminé",
        "chat_started": "Chat démarré",
```

2021-11-16 16:31 UTC, murtaza98 commented on src/i18n/fr.json
> +        "chat_finished": "Chat Terminé",
suggesting this since it was mentioned by the support team over [here](https://open.rocket.chat/group/jwbhsdybxuewsxjcw?msg=NwnxWg32nEjH3FTWD)

2021-11-19 13:46 UTC, KevLehman commented
@tiagoevanp , this one got some conflicts :( and CI is failing again, can you take a look?

2021-11-22 16:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat.Livechat?pullRequest=657) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat.Livechat?pullRequest=657) before we can accept your contribution.<br/>**4** out of **5** committers have signed the CLA.<br/><br/>:white_check_mark: murtaza98<br/>:white_check_mark: tiagoevanp<br/>:white_check_mark: MartinSchoeler<br/>:white_check_mark: KevLehman<br/>:x: cauefcr<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat.Livechat?pullRequest=657) it.</sub>

2021-11-22 17:22 UTC, cauefcr commented
I read most of the changes (those that had little line changes), and saw nothing out of the ordinary, just a painful library change, CI is working well, I just can't comment on front-end best practices or style.

2021-12-08 19:06 UTC, KevLehman approved these changes
Tested functionallity and translations are working.
However, I had to Hard refresh the page up to 2 times before seeing any language change.

2021-12-08 19:06 UTC, KevLehman commented on src/components/Messages/VideoAttachment/stories.js
> -import { VideoAttachment } from '.';
Is this the expected change?

2021-12-09 12:23 UTC, fabiosurrage commented
@tiagoevanp , how to work with this new translations ? Just alter the i18 files and do a _yarn build_ command ? No need of the comand _yarn i18n_ anymore ?

2021-12-16 11:04 UTC, tiagoevanp commented
> @tiagoevanp , how to work with this new translations ? Just alter the i18 files and do a _yarn build_ command ? No need of the command _yarn i18n_ anymore ?

Yes, insert the key with the new translation and everything will work to get the right language translation. 'en' is the default language. The process is similar on what we have in Rocket.Chat/Rocket.Chat repo.

I hope we could introduce some different CI tools to improve the translation files such as in Rocket.Chat/Rocket.Chat repo does.

2021-12-16 13:20 UTC, tiagoevanp commented on src/components/Messages/VideoAttachment/stories.js
> -import { VideoAttachment } from '.';
I can't find this on code 🤔

2021-12-23 11:22 UTC, murtaza98 commented
Hi @tiagoevanp I found the following issues while testing this PR locally. 

- When routing algo is "Manual" and the chat gets in the queue
   ![image](https://user-images.githubusercontent.com/34130764/147232258-1a7085cb-3792-43b2-b6ba-2cf83805b4c8.png)

- Move back to queue system message was missing - no error gets thrown
   ![image](https://user-images.githubusercontent.com/34130764/147232538-e429051f-3f70-45ac-a424-44eec49bf469.png)

- When clicking on the finish chat button
  ![image](https://user-images.githubusercontent.com/34130764/147232752-214b280a-2578-42b5-b039-067eb0904299.png)
  ![image](https://user-images.githubusercontent.com/34130764/147232800-23660dd9-8ee6-409f-a6ae-7376d82634a4.png)

2021-12-23 11:23 UTC, murtaza98 requested changes
Hi @tiagoevanp I found the following issues while testing this PR locally. 

- When routing algo is "Manual" and the chat gets in the queue
   ![image](https://user-images.githubusercontent.com/34130764/147232258-1a7085cb-3792-43b2-b6ba-2cf83805b4c8.png)

- Move back to queue system message was missing - no error gets thrown
   ![image](https://user-images.githubusercontent.com/34130764/147232538-e429051f-3f70-45ac-a424-44eec49bf469.png)

- When clicking on the finish chat button
  ![image](https://user-images.githubusercontent.com/34130764/147232752-214b280a-2578-42b5-b039-067eb0904299.png)
  ![image](https://user-images.githubusercontent.com/34130764/147232800-23660dd9-8ee6-409f-a6ae-7376d82634a4.png)



In all the 3 cases, I got a similar error like this
  ![image](https://user-images.githubusercontent.com/34130764/147245480-1606dba4-ba17-4ac2-b3d8-3ea7de36fef2.png)

2022-03-31 11:38 UTC, murtaza98 approved these changes
LGTM!! Thanks a lot!! The new translation structure is looking much better!!

2022-03-31 15:41 UTC, merged