[NEW] Handle with `removeGuestInfoWhenChatEnded` setting
RocketChat/Rocket.Chat.Livechat pull request #666
Opened 2021-11-29 22:02 UTC by tiagoevanp

2021-11-30 11:54 UTC, renatobecker commented on src/lib/room.js
> +	if (removeGuestInfoWhenChatEnded) {
Visitor won't be deleted, just the session will be clean/reset.

2021-12-01 13:10 UTC, renatobecker requested changes

2021-12-02 17:50 UTC, KevLehman commented on src/store/Store.js
> +		this._state = {};
Hey @renatobecker , can you take a look again?

2021-12-02 18:08 UTC, renatobecker requested changes

2021-12-02 18:08 UTC, renatobecker commented on src/store/Store.js
> +		this._state = {};
It works like a charm now, but we should not change the following fields as they impact UI/UX.
- minimized
- visible
- undocked
- expanded

2021-12-02 18:19 UTC, renatobecker requested changes

2021-12-02 18:19 UTC, renatobecker commented on src/lib/room.js
> +		await store.setState(initialState());
```suggestion
		const { visible, minimized, undocked, expanded, ...newState } = initialState();
		await store.setState(newState);
```

WDYT?

2021-12-02 18:35 UTC, KevLehman commented on src/store/Store.js
> +		this._state = {};
Changes done!

2021-12-02 18:36 UTC, KevLehman commented on src/lib/room.js
> +		await store.setState(initialState());
Yup, did basically the same haha

2021-12-02 18:50 UTC, renatobecker requested changes

2021-12-02 18:50 UTC, renatobecker commented on src/store/Store.js
> +	cleanState() {
This change is no longer needed.

2021-12-02 18:51 UTC, renatobecker commented on src/store/Store.js
> +		this._state = {};
LGTM, but please check [this comment](https://github.com/RocketChat/Rocket.Chat.Livechat/pull/666#discussion_r7613774990)

2021-12-02 19:04 UTC, KevLehman commented on src/store/Store.js
> +	cleanState() {
Removed

2021-12-02 19:29 UTC, KevLehman commented
After store change I had to update storybook, that generated a ton more of changes :(

2021-12-02 20:52 UTC, renatobecker approved these changes

2021-12-03 14:00 UTC, merged